# Generated by Django 6.0.7 on 2026-07-20 15:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'service_category',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('work_start', models.TimeField()),
                ('work_end', models.TimeField()),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=2)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'specialist',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='salon.servicecategory')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='SpecialistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.specialist')),
            ],
            options={
                'db_table': 'specialist_service',
            },
        ),
        migrations.AddField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(related_name='specialists', through='salon.SpecialistService', to='salon.service'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='salon.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='salon.service')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='salon.specialist')),
            ],
            options={
                'db_table': 'booking',
                'indexes': [models.Index(fields=['specialist', 'booking_date'], name='idx_booking_specialist_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['Pending', 'Confirmed', 'Completed', 'Cancelled'])), name='booking_status_check')],
            },
        ),
        migrations.AddConstraint(
            model_name='specialistservice',
            constraint=models.UniqueConstraint(fields=('specialist', 'service'), name='specialist_service_unique'),
        ),
    ]
